# -*- coding: utf-8 -*-
"""Transmetro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wfXcCoTdOeLGgXQVHMxYQH8wSe4SfJ8A
"""

!pip install networkx --quiet

import networkx as nx
import heapq

G = nx.DiGraph()

G.add_edge("Portal Soledad", "La Arenosa", tiempo=3, linea="R1")
G.add_edge("La Arenosa", "Hipodromo", tiempo=4, linea="R1")
G.add_edge("Hipodromo", "Parque Cultural", tiempo=5, linea="R1")
G.add_edge("Parque Cultural", "Joe Arroyo", tiempo=6, linea="R1")
G.add_edge("La Arenosa", "Joe Arroyo", tiempo=10, linea="R2")
G.add_edge("Hipodromo", "Joe Arroyo", tiempo=7, linea="R3")
G.add_edge("Soledad Centro", "Portal Soledad", tiempo=8, linea="A1")
G.add_edge("Barranquillita", "Parque Cultural", tiempo=9, linea="A2")

print("Conexiones en el grafo (origen, destino, atributos):\n")
for u, v, data in G.edges(data=True):
    print(f"{u} -> {v} | tiempo={data['tiempo']} min | linea={data['linea']}")

PENALIZACION_TRASBORDO = 3


def puede_viajar(origen, destino):
    return G.has_edge(origen, destino)


def hay_trasbordo(linea_actual, linea_nueva):
    if linea_actual is None:
        return False
    return linea_actual != linea_nueva


def costo_tramo(tiempo_tramo, hubo_trasbordo):
    if hubo_trasbordo:
        return tiempo_tramo + PENALIZACION_TRASBORDO
    else:
        return tiempo_tramo


def mejor_ruta(origen, destino):


    cola = [(0, origen, None, [(origen, None)])]
    visitados = {}

    while cola:
        costo, estacion_actual, linea_actual, ruta = heapq.heappop(cola)

        clave_visita = (estacion_actual, linea_actual)
        if clave_visita in visitados and visitados[clave_visita] <= costo:
            continue
        visitados[clave_visita] = costo

        if estacion_actual == destino:
            return costo, ruta

        for vecino in G.successors(estacion_actual):
            if not puede_viajar(estacion_actual, vecino):
                continue

            datos = G[estacion_actual][vecino]
            tiempo_tramo = datos["tiempo"]
            linea_nueva = datos["linea"]

            hubo_tras = hay_trasbordo(linea_actual, linea_nueva)

            costo_extra = costo_tramo(tiempo_tramo, hubo_tras)
            nuevo_costo = costo + costo_extra

            nueva_ruta = ruta + [(vecino, linea_nueva)]

            heapq.heappush(cola, (nuevo_costo, vecino, linea_nueva, nueva_ruta))

    return None, []

origen = "Soledad Centro"
destino = "Joe Arroyo"

costo_total, ruta = mejor_ruta(origen, destino)

print("\n")
print(f"RUTA ÓPTIMA DESDE '{origen}' HASTA '{destino}'")
print("\n")

if ruta:
    print(f"Costo total (tiempo + penalización por trasbordos): {costo_total} minutos equivalentes\n")
    print("Detalle de la ruta:")
    for i, (estacion, linea) in enumerate(ruta):
        if i == 0:
            print(f" - Salir desde: {estacion}")
        else:
            print(f" - Tomar línea {linea} hasta: {estacion}")
else:
    print("No se encontró ruta válida entre las estaciones indicadas.")